### ISSUE TITLE
btw i use arch

### ISSUE THREAD

**Issue by alisacorporation** [reptily/install#1]
![ae2](https://user-images.githubusercontent.com/26173604/154601925-c331aac8-66f4-4ddb-9fda-448643cb49b5.png)

```

if test -f /usr/bin/yay; then
    yay -S $1
fi
```

**Comment by iBrabus** [comment]
#!/bin/sh <-- Alpine Linux by default does not have bash?

**Comment by reptily** [comment]
Added support Arch Linux
Thx!
